language: php

sudo: false

php:
  - "7.1"
  - "7.2"

install:
  - composer install --no-interaction --prefer-source

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls

